---
deployment:
  tasks:
    - export DEPLOYPATH=/home/untadsk/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R gambar $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
